### PR TITLE
Added Sort Assemblies command to Assembly Explorer context menu

### PR DESCRIPTION
**Pull request by SlowLogicBoy**
image

### CODE REVIEW

**Comment by 0xd4d** [comment]
👍 except for the spaces and ` ()` (space before open paren)

**Comment by SlowLogicBoy** [comment]
Dang it I always forget the spaces. It's difficult to work with multiple styles :D

**Comment by SlowLogicBoy** [comment]
Should be good now.

**Comment by 0xd4d** [comment]
Thanks.

The duplicated code is minimal, it's just calling the real sorter code.

**Pull request merged**
