### PR TITLE
Change some C# 7 code to C# 6

### PR DESCRIPTION
**Pull request by HoLLy-HaCKeR**
Changes some of my C# 7 code to C# 6, so it can be built with Visual Studio 2015.

This is in response to issue #510.

### CODE REVIEW

**Comment by HoLLy-HaCKeR** [comment]
Just in case I can contribute something in the future: should I write C# 6 code and commit to master to create C# 7 code and commit to dbg?

**Comment by 0xd4d** [comment]
> should I write C# 6 code and commit to master to create C# 7 code and commit to dbg?

No, just one branch is enough. C#6 in master (for now, that will soon change), and in dbg I use the latest version.

**Comment by HoLLy-HaCKeR** [comment]
Typo, I meant if I had to commit to master (in C# 6) or dbg (in C# 7).

**Comment by 0xd4d** [comment]
Commit to master unless it has to be in dbg, eg. if you're updating the debugger it would have to be the dbg branch because the debugger in master is the old one and has been removed.

**Pull request merged**
