### PR TITLE
Adjust namespace color in light and blue theme

### LINKED ISSUE #148: Fix some light/blue colors
Eg. namespace color is too similar to the class color

### PR DESCRIPTION
**Pull request by patricksadowski**
Closes #148

### CODE REVIEW

**Comment by patricksadowski** [comment]
@0xd4d: Please review

**Comment by 0xd4d** [comment]
It's better, but I think it should be easier to see the namespace. Compare it to the namespace color in the dark theme, you can instantly see it because the namespace color and type color are so different. To see an example, switch to IL mode.

**Comment by patricksadowski** [comment]
I've updated the commit.

**Comment by 0xd4d** [comment]
Thanks, looks better!

**Pull request merged**
