### PR TITLE
RoutedEventRecord: Read and write data in same order when serializing.

### PR DESCRIPTION
**Pull request by josteink**
This closes https://github.com/0xd4d/dnSpy/issues/1262.

### CODE REVIEW

**Comment by 0xd4d** [comment]
According to the ref source, there should be 2 fields only, so `Reserved1` field can be removed

https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Markup/BamlRecords.cs,cb7196ed823948a0

**Comment by josteink** [comment]
PR updated.

**Comment by 0xd4d** [comment]
Thanks for the fix!

**Comment by josteink** [comment]
Glad to be of service. Thanks for a great tool!

**Pull request merged**
