### PR TITLE
AntiAntiDebug - IsDebuggerPresent (kernelbase.dll) bypass

### LINKED ISSUE #1358: AntiAntiDebug - IsDebuggerPresent (kernelbase.dll) bypass
- What version did you use?
dnspy v6.1.1 64bit

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Dnspy bypasses IsDebuggerPresent from kernel32.dll but not from kernelbase.dll
Example exe attached

Please add kernelbase's IsDebuggerPresent to dnspy antiantidebuggers.

[AntiDebugTester.zip](https://github.com/0xd4d/dnSpy/files/4018829/AntiDebugTester.zip)

### PR DESCRIPTION
**Pull request by InlineAsm**
This PR fixes #1358 

I did not want to change too much so it's basically a copy of the IsDebuggerPresentHook classes.

### CODE REVIEW

**Comment by 0xd4d** [comment]
Have you tested this on Windows 7?

**Comment by InlineAsm** [comment]
No, I tested with Windows 10. I can test on Windows 7. Will let you know.

**Comment by InlineAsm** [comment]
Ok, I tested on Windows 7 64-bit edition. It works.

**Comment by 0xd4d** [comment]
Thanks again!

**Pull request merged**
