### PR TITLE
Improve UI performance

### PR DESCRIPTION
**Pull request by yck1509**
Improve the general performance and responsiveness of treeview and text rendering.
Requires my edit of AvalonEdit (see [my pull request](https://github.com/0xd4d/AvalonEdit/pull/1)).

### CODE REVIEW

**Comment by 0xd4d** [comment]
I've tested the new code and here are my comments.

SHORT:

I think the biggest speed up will come from caching the TV nodes, since that's where most CPU cycles go. FastVirtualizingSP is a speedup too and can of course still be used to get a little better performance.

Text teditor scrolling is faster. hex editor: I didn't notice any difference in speed.

LONG:

TreeView no stx hilite w/ CACHE
-------------------------------

- Probably better to use a WeakReference as a cache or will the cached elements be GC'd too quickly?
- when language is changed, the text isn't updated. You must clear the cache when that happens. See OnFilterSettingsChanged().
- Why aren't you caching syntax highlighted output?

TreeView stx hilite, VirtualizingSP
-----------------------------------

- Scrolling up/down is now slower than before, the old code used Standard but your new code now sets it to Recycling.

Try this: use scroll bar to scroll up and down several times.

The elems are cached internally by the scrollviewer (probably). Once you release the mouse the cached elems are freed. When you use Recycling, the ListBoxItem's are recycled and their contents are re-generated every single time. I.e,. recycling just recycles the XXXItems, it doesn't cache the XXXItems' contents.

TreeView Stx hilite FastVirtualizingSP
--------------------------------------

There seems to be a small improvement over the previous code but I'm not 100% sure about that (I only measured using my eyes, I didn't use a timer). The original code is faster once the automatic caching kicks in since the original code uses Standard instead of Recycling.

Do you see a bigger speed improvement than I do?

The slowest part of the TV is generating the nodes, so if you cache the elements (eg. with WeakReference), it might turn out that the TV layout display panel options might not be needed, i.e., using the default VirtualizingSP might be good enough.

Text editor
-----------
- The scrolling does seem faster! (again, I only used my eyes, didn't add a timer to the code)
- Pressing END on a line with tabs doesn't always move the caret to the last character on the line. Seems to be a tab vs spaces issue.
- The text size changes when switching to GlyphRunFormatter. Is it possible to keep the same text size? Would be easier to compare performance too since right now with GlyphRunFormatter enabled, it shows less lines.

Hex editor
----------
- Unfortunately I couldn't notice any difference in speed here.
- The hex editor isn't always refreshed to use the new GlyphRunFormatter code. Open the hex editor, change option, and press OK, and the screen isn't refreshed. Repeat the procedure and it gets updated.

**Comment by yck1509** [comment]
Thanks for the review! :smile:

- In my profiling of the original code, most of the time is spent in TreeView is on applying templates (i.e. adding TreeNodes to the panel, i.e. Recycling mode & FastVirtualizingPanel), second is data binding and text rendering (i.e. SharpTreeNodeProxy & FastTextBlock).

- FastVirtualizingPanel aims at optimizing in Recycling mode to reduce delays in scrolling. In Standard mode, scrolling has an initial lag (due to template applying) but all instantiated items are cached during the scrolling, so the speed is quite inconsistent. In Recycling mode, scrolling has a much more consistent speed, although a bit slower. Personally I prefer a consistent scrolling speed as most probably you won't keep scrolling for 10 seconds to feel their difference in actual use. :P

- Personally I do not use syntax highlighting treenodes so the optimization does not target them. However it seems you use it so I'll optimize it to use new rendering methods.

- GlyphRunFormatter is definitely one of the most troublesome to implement. I had just made some fix to it, but still cannot achieve identical rendering as WPF's one. :P I guess there is some trade-off between performance and quality.

- The hex editor should not have much performance increase, as the rendering is already very fast enough. :) Also, I can't find a way to force refresh HexBox. Is there a way to do so?

- One more performance patch would be coming in, I'll finished it before pushing the new code to the branch. In the meanwhile, I've updated the perf branch of AvalonEdit to match the font size, please review and merge it.

**Comment by 0xd4d** [comment]
TreeView
--------

I still can't see a performance increase in the treeview. I tried:

- no syntax highlighting
- Virtualization mode: Recycling
- Panel: VirtualizingStackPanel vs FastVirtualizingPanel
- Expanded every namespace in mscorlib 4.0 and scrolled up and down using the scroll bar.

I didn't notice any difference using my eyes. When I checked Task Manager, I didn't notice any CPU difference either (it max outs one CPU in both tests).

Pressing and holding down the lower scrollbar button and scrolling down that way resulted in the same CPU usage in both tests.

Can you see the difference or can you only measure a difference, and if so how much faster is the code now?


Text Editor
-----------
I did a similar test as above but with the text editor. Here I did notice a CPU usage improvement with your new code! I had selected mscorlib 4.0's resources node (~3000 lines of text).

In my tests, the old code was about 30% slower (used 30% more CPU).


Virtualization mode default
----------------------------------

IMHO, Virtualization mode doesn't belong in the settings. It's just a specialized option that most people don't know what it is or would want to change.

`Recycling`, that you prefer, should be the default, it does perform much better than `Standard` that dnSpy currently uses.

**Comment by 0xd4d** [comment]
BTW, you need to add a new PR for your latest AvalonEdit commit since that PR was closed when I merged the first one. I did test it though and it fixed the END bug. :)

**Comment by yck1509** [comment]
About TreeView: Are you using commit 8bfc63feee with FastVirtualizingPanel, Recycling & GlyphRunFormatter? Here it has a significant improvement that the scrolling of TreeView is almost at same speed as TextView.

**Comment by 0xd4d** [comment]
Yes I'm using that commit including the latest AvalonEdit fix.

And now for something weird...

I did also write that the text editor code was faster, but I only compared against the BuiltIn using the same binary. I've now compared it against the latest build from the build server: https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts and that one is *faster*. NOTE: all tests are using Release builds.

In my tests, holding down the scrollbar's down button uses ~10% CPU usage using the latest dnSpy build on the build server. With your changes, BuiltIn (same test) is using 32% CPU usage, and GlyphRunFormatter is using 25% CPU usage. I don't know what's going on here since BuiltIn should use the same 10% as the one on the build server.

Maybe I've made some mistake somewhere. (BTW, the code hasn't been modified, git still says that everything is clean, and I'm only testing Release builds, I'm also running the exes **without** a debugger, testing dnSpy-x86.exe in all tests).

dnSpy:

```sh
$ git log -1
commit 8bfc63feee4f6a2a0e78703d0442aae034c7958e
Author: yck1509 <confuser.net@gmail.com>
```

AvalonEdit:

```sh
$ git log -1
commit e5807fe1f8185b00f3e121c131844916104685d5
Author: yck1509 <confuser.net@gmail.com>
```

Could it be a HW issue here, or have I made a mistake somewhere?

**Comment by 0xd4d** [comment]
I'm seeing the same problem with the hex editor. It' uses ~7% with the older dnSpy binary but 25% vs 32% with the latest changes (same as with the text editor).

**Comment by yck1509** [comment]
Do you have dedicated graphics card? Maybe try using the methods in https://stackoverflow.com/questions/149763/how-do-you-determine-if-wpf-is-using-hardware-or-software-rendering to see whether you are using hardware acceleration? If you don't mind, I could send my binaries to you to test is there any problem in compilation.

**Comment by yck1509** [comment]
Also, if you don't mind, you could use ANTS profiler (which I used) to see which part uses most CPU (I use method-level all-methods settings).

**Comment by 0xd4d** [comment]
The problems have been fixed and I can now see the speedups, and they're especially noticeable in the treeview.

I did notice now in your new commits above that you say that unicode and word wrap aren't supported. Word warp isn't so important, but unicode might be to some people. By unicode, do you mean every unicode char 0x100 and above?

Is it possible to get unicode support or is it too difficult? If not, it might be better to not enable this by default since some people will think there's something wrong with the text editor.

**Comment by yck1509** [comment]
By Unicode, I mean the substitution of FontFamily for Unicode characters. If the FontFamily does not have the character required, GlyphRunFormatter would not use another FontFamily that has it as WPF's does. I suppose I'll turn it off by default.

**Comment by xy9144** [comment]
How to use plugins，just like ILSpy.

**Pull request merged**
