### PR TITLE
Implement issues #338, #78

### PR DESCRIPTION
**Pull request by HardToChoose**
Allow sorting in Locals and Modules windows.

### CODE REVIEW

**Comment by 0xd4d** [comment]
I'm rewriting most of the debugger front end code, see the dbg branch. You've unfortunately modified old (and soon to be deleted) code.

This PR sorts the children in the locals window (try to expand an array or a class with fields/props). This is bad if there are lots of child elements because when you sort, you must know the text and the only way to get the text is to ask the CLR debugger to evaluate the expression which is an expensive operation, especially if eg. ToString() is called. Another problem is that a child could be sorted above its parent, this looks weird. ;)

When I tested this and I expanded a class, an assert in ValueVM.cs triggered in `CleanUpCorValue()` (`context` is null).

I think a better solution is to let the debug engine return a sorted list of elements to show in the UI. That way all args are shown at the top ordered in method signature order followed by locals (sorted by name).

The modules window code works (minus the arrow on the column header indicating sort direction). IMHO, the sorting logic belongs in the VM, not the UI, code. Eg. you could use a ListCollectionView to sort and filter items, but if it's in the VM, it can be used by any UI using the VM. This is what the new modules window does when searching, the VM filters the list, not the UI. It's probably easy to add sorting to this list too and have the UI update when it's sorted.

**Comment by HardToChoose** [comment]
Thanks for the review.
Is it worth to re-implement the sorting logic for Modules window in the dbg branch,
or it's just a matter of 20 min of coding for you? :)

**Comment by 0xd4d** [comment]
You can do that if you want, see `ModuleVMComparer` which is used to sort the list.

**Comment by 0xd4d** [comment]
Continued in #425

**Pull request closed without merging**
