### PR TITLE
Fixing xml-doc references

### PR DESCRIPTION
**Pull request by hmemcpy**
This prevents ReSharper analysis errors

### CODE REVIEW

**Comment by 0xd4d** [comment]
What error do you get from ReSharper? The cref was generated by VS2015 so should be accepted by anyone who parses XML documentation.

**Comment by hmemcpy** [comment]
For some reason, ReSharper (I'm using 10.0.2) doesn't like the `ResourceElement` parameter in the signature:

image

Removing it makes the error disappear, however it still generates a proper documentation:

image

No idea if this is an actual error, but it makes ReSharper shut up :)

**Comment by 0xd4d** [comment]
Is that the only file ReSharper has a problem with or does it show such an error for almost every file?

**Comment by hmemcpy** [comment]
Yeah, that's the only thing. I'm running with Solution-wide analysis enabled, and this is the only thing it flags.

**Comment by hmemcpy** [comment]
Awesome! Thanks a lot :)
BTW, *amazing* job with the tool, I can't believe how extensible this is! Thank you!

**Pull request merged**
